<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I87EVTQ" failures="1" tests="1" name="Bank Manager Login Test" time="0.409" errors="0" timestamp="2021-12-17T17:30:04 IST">
  <testcase classname="com.w2a.testcases.BankManagerLoginTest" name="loginAsBankManager" time="0.23">
    <failure type="java.lang.AssertionError" message="Login not successful">
      <![CDATA[java.lang.AssertionError: Login not successful
at com.w2a.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- loginAsBankManager -->
</testsuite> <!-- Bank Manager Login Test -->
