<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I87EVTQ" failures="1" tests="8" name="com.w2a.testcases.AllUnitTestCases" time="0.419" errors="0" timestamp="2021-12-20T12:49:30 IST" skipped="7">
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="createUnitWithBlankData" time="0.419">
    <failure message="Test case forcefully failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case forcefully failed
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.AllUnitTestCases.createUnitWithBlankData(AllUnitTestCases.java:386)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- createUnitWithBlankData -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="createUnitWithBlankUnit">
    <skipped/>
  </testcase> <!-- createUnitWithBlankUnit -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="c_clickingOnUnitButton">
    <skipped/>
  </testcase> <!-- c_clickingOnUnitButton -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="clickingOnBackButton">
    <skipped/>
  </testcase> <!-- clickingOnBackButton -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="b_editUnit">
    <skipped/>
  </testcase> <!-- b_editUnit -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="createUnitWithBlankName">
    <skipped/>
  </testcase> <!-- createUnitWithBlankName -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="d_deleteUnit">
    <skipped/>
  </testcase> <!-- d_deleteUnit -->
  <system-out/>
  <testcase classname="com.w2a.testcases.AllUnitTestCases" name="a_addUnit">
    <skipped/>
  </testcase> <!-- a_addUnit -->
  <system-out/>
</testsuite> <!-- com.w2a.testcases.AllUnitTestCases -->
